import React from 'react'
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from '@react-pdf/renderer'
import type { DocResult } from '@/types'

const styles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 64,
    paddingHorizontal: 40,
    fontFamily: 'Helvetica',
    backgroundColor: '#FFFFFF',
  },
  title: {
    fontSize: 24,
    fontFamily: 'Helvetica-Bold',
    textAlign: 'center',
    marginBottom: 20,
    color: '#111827',
  },
  rule: {
    borderBottomWidth: 0.5,
    borderBottomColor: '#D1D5DB',
    marginBottom: 22,
  },
  section: {
    marginBottom: 18,
  },
  heading: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 5,
    color: '#1F2937',
  },
  content: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#4B5563',
  },
  pageNumber: {
    position: 'absolute',
    bottom: 32,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 9,
    color: '#9CA3AF',
  },
  footer: {
    position: 'absolute',
    bottom: 18,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 7,
    color: '#D1D5DB',
  },
})

function PdfDocument({ docResult }: { docResult: DocResult }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{docResult.title}</Text>
        <View style={styles.rule} />
        {docResult.sections.map((section, i) => (
          <View key={i} style={styles.section}>
            <Text style={styles.heading}>{section.heading}</Text>
            <Text style={styles.content}>{section.content}</Text>
          </View>
        ))}
        <Text
          style={styles.pageNumber}
          render={({ pageNumber, totalPages }) =>
            `${pageNumber} / ${totalPages}`
          }
          fixed
        />
        <Text style={styles.footer} fixed>
          Generated by PasteDoc
        </Text>
      </Page>
    </Document>
  )
}

export async function buildPdf(docResult: DocResult): Promise<Buffer> {
  const buffer = await renderToBuffer(<PdfDocument docResult={docResult} />)
  return Buffer.from(buffer)
}
